---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      volumes:
      - name: static-files-volume
        emptyDir: {}
      initContainers:
      - name: copy-static
        image: harbor.0l.de/stv0g/gose
        command:
          - cp
          - -r
          - /dist
          - /static-files
        volumeMounts:
        - mountPath: /static-files
          name: static-files-volume
      containers:
      - name: nginx
        image: nginx:1.17-alpine
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: static-files-volume
          subPath: dist
        resources:
          limits:
            memory: 250Mi
            cpu: "1"
          requests:
            memory: 250Mi
            cpu: "500m"
