---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gose
spec:
  ingressClassName: nginx
  rules:
  - host: gose-test.0l.de
    http:
      paths:
      - path: /api/
        pathType: Prefix
        backend:
          service:
            name: backend
            port:
              number: 8080

      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80
