listen: ":8080"

# All settings from the servers section can also be used in the global section
# to provide defaults across all configured servers. E.g.
max_upload_size: 1TB

# A list of servers/buckets which the user can select in the frontend
# The first server is selected by default
servers:
- bucket: gose-uploads

  endpoint: s3.0l.de
  region: s3

  path_style: true
  no_ssl: false

  # Or via standard AWS_ACCESS_KEY_ID/AWS_SECRET_ACCESS_KEY env vars
  access_key: ""
  secret_key: ""

  max_upload_size: 5TB
  part_size: 16MB

  # A list of expiration/rentention classes
  # The first class is selected by default
  expiration:
  - id: 1day
    title: 1 day
    days: 1
  - id: 1week
    title: 1 week
    days: 7
  - id: 1month
    title: 1 month
    days: 31
  - id: 1year
    title: 1 year
    days: 365

shortener:
  # Example for self-hosted shlink.io:

  # Available template args:
  #  .Url
  #  .UrlEscaped
  endpoint: "https://shlink-api/rest/v2/short-urls/shorten?apiKey=<your-api-token>&format=txt&longUrl={{.URLEscaped}}"
  method: GET
  response: raw

notification:
  # See: https://containrrr.dev/shoutrrr/v0.5/services/overview/
  urls:
  - pushover://shoutrrr:<api-token>@<user-key>?devices=laptop1&title=Upload
  template: |
    URL: {{.URL}}
    File: {{.FileName}}
    Size: {{.FileSizeHuman}}
    Type: {{.FileType}}
    Uploaded at: {{.UploadDate.Format "Jan 02, 2006 15:04:05 UTC"}}
    Uploaded by: {{.UploaderIP}} ({{.UploaderHostname}})
    Expires  at: {{.ExpiryDate.Format "Jan 02, 2006 15:04:05 UTC"}} ({{.ExpiryRuleID}})

  # For user notifications
  mail:
    url: smtp://user:password@host:port/?fromAddress=max@example.com
    template: |
      URL: {{.URL}}
      File: {{.FileName}}
      Size: {{.FileSizeHuman}}
      Type: {{.FileType}}
      IP: {{.UploaderIP}} ({{.UploaderHostname}})
