s3:
  bucket: gose-uploads

  endpoint: s3.0l.de
  region: s3

  path_style: true
  no_ssl: false

  # Or via standard AWS_ACCESS_KEY_ID/AWS_SECRET_ACCESS_KEY env vars
  access_key: ""
  secret_key: ""

  max_upload_size: 5TB
  part_size: 16MB

  expiration:
    default_class: 1week # one of the tags below

    classes:
    - tag: 1day
      title: 1 day
      days: 1
    - tag: 1week
      title: 1 week
      days: 7
    - tag: 1month
      title: 1 month
      days: 31
    - tag: 1year
      title: 1 year
      days: 365

server:
  listen: ":8080"

shortener:
  # Example for self-hosted shlink.io:

  # Available template args:
  #  .Url
  #  .UrlEscaped
  endpoint: "https://shlink-api/rest/v2/short-urls/shorten?apiKey=<your-api-token>&format=txt&longUrl={{.URLEscaped}}"
  method: GET
  response: raw

notification:
  # See: https://containrrr.dev/shoutrrr/v0.5/services/overview/
  urls:
  - pushover://shoutrrr:<api-token>@<user-key>?devices=laptop1&title=Upload
  template: |
    URL: {{.URL}}
    File: {{.FileName}}
    Size: {{.FileSizeHuman}}
    Type: {{.FileType}}
    IP: {{.UploaderIP}} ({{.UploaderHostname}})
