s3:
  bucket: "upload"
  endpoint: "s3.0l.de"
  path_style: true
  region: "s3"
  no_ssl: false

mpu:
  enabled: true

server:
  bind: ":8080"

shortener:
  endpoint: "https://l.0l.de/rest/v2/short-urls/shorten?apiKey=952eee41-ad41-4743-8e7c-a1571168fd22&longUrl={{.Url}}"
  method: POST
  response: raw
